In [5]:
a=int(input("Enter no.of rows:"))
b=int(input("Enter no.of columns:"))
matrix= []

print("Enter elements row wise:")
for i in range(a):
    c=[]
    for j in range(b):
        c.append(int(input()))
    matrix.append(c)

for i in range(a):
    for j in range(b):
        print(matrix[i][j],end=" ")
    print()
    

Enter no.of rows: 2
Enter no.of columns: 2


Enter elements row wise:


 1
 2
 3
 4


1 2 
3 4 


In [15]:
import numpy as np
a=int(input("Enter no.of rows:"))
b=int(input("Enter no.of columns:"))
matrixa= []

print("Enter elements row wise:")
for i in range(a):
    c=[]
    for j in range(b):
        c.append(int(input()))
    matrixa.append(c)
matrix=np.array(matrixa)
res=matrix.transpose()
print(res)


Enter no.of rows: 2
Enter no.of columns: 2


Enter elements row wise:


 1
 2
 3
 4


[[1 3]
 [2 4]]


In [29]:
import numpy as np
a=int(input("Enter no.of rows:"))
b=int(input("Enter no.of columns:"))
matrixa= []

print("Enter elements row wise:")
for i in range(a):
    c=[]
    for j in range(b):
        c.append(int(input()))
    matrixa.append(c)

d=int(input("Enter no.of rows:"))
e=int(input("Enter no.of columns:"))
matrixb= []

if b==d:
    print("Enter elements row wise:")
    for i in range(d):
        f=[]
        for j in range(e):
            f.append(int(input()))
        matrixb.append(f)
    result=np.dot(matrixa,matrixb)
    print(result)
else:
    print("Error! Row and column size should be same")


Enter no.of rows: 2
Enter no.of columns: 2


Enter elements row wise:


 1
 2
 3
 4
Enter no.of rows: 2
Enter no.of columns: 2


Enter elements row wise:


 5
 6
 7
 8


[[19 22]
 [43 50]]


In [17]:
import numpy as np
a=int(input("Enter no.of rows:"))
b=int(input("Enter no.of columns:"))
matrixa= []

print("Enter elements row wise:")
for i in range(a):
    c=[]
    for j in range(b):
        c.append(int(input()))
    matrixa.append(c)
matrix=np.array(matrixa)
res=np.linalg.inv(matrixa)
print(res)


Enter no.of rows: 2
Enter no.of columns: 2


Enter elements row wise:


 4
 6
 8
 10


[[-1.25  0.75]
 [ 1.   -0.5 ]]


In [20]:
import numpy as np
a=int(input("Enter no.of rows:"))
b=int(input("Enter no.of columns:"))
matrixa= []

print("Enter elements row wise:")
for i in range(a):
    c=[]
    for j in range(b):
        c.append(int(input()))
    matrixa.append(c)
matrix=np.array(matrixa)
res=np.linalg.matrix_rank(matrixa)
print("Rank of matrix:",res)


Enter no.of rows: 2
Enter no.of columns: 2


Enter elements row wise:


 1
 2
 3
 4


Rank of matrix: 2
